### ISSUE TITLE
Could not find validator in the list of imported crates

### ISSUE THREAD

**Issue by remykarem** [somehowchris/rocket-validation#14]
I get the following error when going through the json example:

```
 --> src/main.rs:7:41
  |
7 | #[derive(Debug, Deserialize, Serialize, Validate)]
  |                                         ^^^^^^^^ could not find `validator` in the list of imported crates
```

example from https://github.com/somehowchris/rocket-validation/tree/main/examples/json-validation

```rust
#[macro_use]
extern crate rocket;

use rocket::serde::{json::Json, Deserialize, Serialize};
use rocket_validation::{Validated, Validate};

#[derive(Debug, Deserialize, Serialize, Validate)]
#[serde(crate = "rocket::serde")]
pub struct HelloData {
    #[validate(length(min = 1))]
    name: String,
    #[validate(range(min = 0, max = 100))]
    age: u8,
}

...
```

But after I added `validator` as a dependency, it compiles.

Should we update the docs to include this dependency?

**Comment by somehowchris** [comment]
Thanks a lot for the issue. Somehow I didn't yet come across this issue (as I usually needed to use `validator` anyways) but it's an interesting issue.

It originates as the `Validate` derive will expand into code like this

```rs
impl ::validator::Validate for HelloData {
    fn validate(&self) -> ::std::result::Result<(), ::validator::ValidationErrors> {
        use ::validator::ValidateArgs;
        self.validate_args(())
    }
}
```
Which assumes that there is a module called `validator` aka the crate itself. It's like the `serde ` one where `rocket` reexports the crate so we can use `#[serde(crate = "rocket::serde")]`.

Can't really see any other way than adding `validator` as a direct dependency right now. Will look into this tomorrow.

**Comment by remykarem** [comment]
Great, thanks!

**Comment by somehowchris** [comment]
I'm so sorry. Got caught up in some stuff.

Added a line to the readme

**Comment by remykarem** [comment]
Awesome, cheers!
